### ISSUE TITLE
Just all post chronological

### ISSUE THREAD

**Issue by tomkeysers** [NathanPJF/shopify_latest-blog-post#1]
Hi,

Nice workarounds. What are your thoughts on listing just all posts from multiple blogs chronologically?

I'm looking for that ...

Regards

**Comment by NathanPJF** [comment]
@tomkeysers For something like that I'd recommend using ajax in combination with a JS-based template language like http://handlebarsjs.com.  You can use ajax to call multiple pages that exist on your site for their content, then use a handlebars to re-order the content for you.   For the ajax, it's very similar to how a "load more" button would work.

It's definitely more advanced, but in the long term may be in your best interest.  Over time, your multiple blogs will grow in content and relying on liquid to loop through so much content risks exceeding the memory limit put in place by Shopify.  May take a bit to process on the JS side if you don't put some sort of constraint in place - like only calling the first page of the individual blog posts.

If you're unfamiliar with handlebars, take a look at the ajax cart in Shopify's free theme Brooklyn.

Closing this issue since it's not directly about the code I wrote; but hopefully you find that helpful.
